# Generated by Django 2.2.16 on 2022-06-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220602_0807'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('title', 'author')},
        ),
    ]
